apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:M7B9X/v4SjBfB/EfXgwEYz8BYBtolt2C9tvGfmQkUVDEpSM7qCrAhA==,iv:urwc7L0gGDdT94Ao4P8DbgHVdSzLQOK6iw52bjUCAok=,tag:vQo9lj4G0GK8JlhRJuJnRQ==,type:str]
sops:
  age:
    - recipient: age16j9w80ug9xx2cuq5qav6n69c3uuvmt4dlqys2y3l24lmqh72a4csuevy68
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYOXNvdXhVcm0wZTdHSzlW
        RzZpaDFhWEZwZ0duWlF3M3BoZHFhZTVzUTNZCnBGS2pjM3NyNHVCZDhQZDZHdTFn
        eEsyeWVNczRiQnd6bVViUTlES0V4UFkKLS0tIGUybjVHSzM3b1RjOU9kOUdHSGxL
        T1d4WG50TllzOWkzRGRWWllCVzMxWkkKAdqrwVNpw08PevQtn1vfCOKTrxEzYfWe
        7LzpcymNC3Mjpmths0XMVTYUvmnkeUodFWKGsY2LbSobq+05S13XJg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-24T19:30:01Z"
  mac: ENC[AES256_GCM,data:L9LunOy6r0TS0fhQtoNyLX6fOtjrzEj0dHkbXpeV7eH9uKsR/CH8QcZxe+WXzDTKJWNJy24oR+KkAOVkateSwL0NYLp7bSRXVhuZYr++y6ixxtCG6CMNIl1CIeAExO/RWZfH+Lmz9LwEoGKucmezWxdx+qLdfOiOHoM7ILZoml0=,iv:Y2QPJNAuyXe+P/R9uGDxzjHzKSzt0CZThYxoYhEMXNY=,tag:qLrmwaLB1Nr2tCjD33V5kQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
