apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:DTXJ3Rrjnc1FYPMo3Vb30hcdADqc4FrhQ8y5DSocI1TsGE3wpvZZ9w==,iv:Cd5gvPGMQojOz2tivQrLcntJLilF3zc53JEqtxHkvo8=,tag:oWBbTV4jQnDvYkgsQsIByA==,type:str]
sops:
  age:
    - recipient: age16j9w80ug9xx2cuq5qav6n69c3uuvmt4dlqys2y3l24lmqh72a4csuevy68
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxOUEzeDQzTmozWGE5VjVk
        SDRJK2FFT1BkaTVwWHNDVjJxOVNwc1hzdWpJCmo0UlFWa0J0cG5aSytZNGMvUkVO
        Q3Nza1VTNDZZcFA4L2Z6RFZQSXZTakEKLS0tIFpsQm1PdHhtNEoyY1lIMzZ3ODVF
        VTNIdUlVMWtzMUJ2K1lEc1J6aWZPQUEKCLE8dzdY/BKsOBnrv7ZZUQ9FaWvltUBB
        2+m5vh5sdE18pySlDfcwSdAoKj4WvNrXe1AeGHqY32st0YqtwSJw0Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-24T15:23:30Z"
  mac: ENC[AES256_GCM,data:sd37BPmbweE7t9Long4JMKETNLkzb2/yqm5lK+msWJC9e9+wE7mwy4I+lV1NAGaiGEYxtQIu00PFq0/+2+dDb4LVLJ3qTRnmbJcCy8TzMSGUMAWhEg23MOoYNFvXiM4K07oVIzgJT0H/Uv40VVAehZeqtiG3HS2m6JhGE+q9fBg=,iv:dp72aKwElmaSGMSs6PWj9c9xLKXf2ED9L3q7pAzNNVo=,tag:cFwNxdhLzwTAvCiRWarcJQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
