apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:XwRKZOvJ1MzvE0qYDq4K,iv:IelGJJFMvTpLuBU0/p2Gk4EgXrhvlDYfU5vScgSSafo=,tag:4HKkVlauz4+Z3Y6eXnKkPw==,type:str]
sops:
  age:
    - recipient: age16j9w80ug9xx2cuq5qav6n69c3uuvmt4dlqys2y3l24lmqh72a4csuevy68
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPWlNhVnNqUFFQL2lVYmhn
        U1Q5R1Fub3dKYm1RU3V3MU0rWEZlb0JqL0hzCjdBSmhUR0craVlMN0d4ZXhSL0tS
        bkZqWE55cXlaZlExTE5uV1F1amkrWkkKLS0tIHVMbFhHMTFRV0FMdG9pYS8rWER6
        aFdaMVRwMVFFYnQ4UDJVenp0UjBxR28KLrjSQy3ueyyIHqNxlJWmwIy0M6SCyPYG
        LawtclRk9w5OsmcvOsMRXT8aMZsXjq7f4n3cD5wejnJ5Ejt9JPA+1w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-24T19:30:00Z"
  mac: ENC[AES256_GCM,data:LPX7yk7wHuWQdoBnvWiqSutBX/d0L2TT+cPPzF9ZMEaNAJUvNRUB6Qtlyg2TYhFBWsgcoKyOeAL8dMu/LP3bnVOrC2xdSQnvvVgq9maspc5uF30+ynhDDRf2MgFhBFGVhH2Vs7cEprH1NtsTSRNA4iP4wo/5c9GuoASvnbpcvpQ=,iv:VXzphx4nYi/o8zHOt32eqUpCfHrn7qPs3O5R/GwMXZc=,tag:wfzzTYjE/2qi9kLxcwIeyw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
