apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:kpaboHTIi3HKkbMhzdXl,iv:1hTZBNEpcMHlt9C6zpzT1WW5VK6mO2dE2nVmAfltHNI=,tag:c0KidE608BhgjPSeH92jKQ==,type:str]
sops:
  age:
    - recipient: age16j9w80ug9xx2cuq5qav6n69c3uuvmt4dlqys2y3l24lmqh72a4csuevy68
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzL1RJOVppZHN0V1pManVP
        L2IrT0Iwd0VGdjFDUDcyUnE0S1o3a3hVWVVVCkk4M2dISFhGYmhzRmNnQTlQZENp
        LzZCU1RHcTVaUzdXRzE5VEs3ZkZJejAKLS0tIE44c1AvZVhqK3pmNTFUNklUNmRk
        R2E2bzMzK3NEaEp0ME8yQWt3Yngrb2MKWbJBdzDzzt+ACRTA3HejhrT6ysigOWn9
        VAiiric1uLao2OtJrUewSyECT+B85ZhUPokeXgVYYXHEhN+qMM10TA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-24T15:23:30Z"
  mac: ENC[AES256_GCM,data:QImf1BkPRCAP9XrCh734OHj4su0F6x0XUNr+UPyYNHEnNUMsxPf81A2DTIxsgNH8MKtdPxQ3UHCHssSi37HC/LpROxN3fNx0jsigx5iTD/FX0lO+ZdWClODSU1K4DgIteUVQ/WgnY+l6K4J8fM8ybgypiS3j1zL5vfdTxROmLMM=,iv:sOO5IQfYFUUudyA38CMG1L4JnSIz1uyuMLRmCYpkysY=,tag:dHtowdMmaA58gVySyau+Qg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
