# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:02IGXq+b3yklIRydgCenUu/yrWyrhrQyM224wPCKHgI=,iv:HPAYMoU+v8YJbPtV+wCmeFGX35nqoxVH0vC2HWKuy7g=,tag:DsRrZjJ/WHNvqQyTVGONHg==,type:str]
sops:
  age:
    - recipient: age17xhzltzn39ue9gvrv8te7jcf2ns8fz6w07h6djeu20xfucf4vg7sx5ctc6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBleHhudlVqRjFhRW90ZkV5
        WkowUytkV2crL3gwUnJPaGhMbmQ3VGwrckZrCjNLUTVMQUt5ckNWWDhDYzVGUXpz
        cVBVSGdIUU44R25XS0FyTVBIanhPcHMKLS0tIHBvcmI2TmVSS3pkUjRGejY2Qk80
        SWp4R0F3MWZmMkxhTytOb2thS1pmVFUKvJgO8xF5W1/orMYxlYOFDx4+fiX7oYU0
        jHFRQ0hKM/9Xrb7Njrru9A+IS2nVCB28DRFYC7B9G76rZbJbrfPnJA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-20T21:31:31Z"
  mac: ENC[AES256_GCM,data:gES+n+t8xDFzv1HFmfMKA8FUpdLwcxE8m5u8Q4OgdBnfpfE36kKH+xdDr8fxx/QGlzH9I/cJK4HY3CV+qQMy7q6vOBSsGtSUi+MDj2VdPfziqtGXWHVyqSxbdqgIf6nihwrfdlHlxnFqHO3xeSebBNKyExFCuhzKfOrObRQmWuM=,iv:yQf/yLHQoOaf3iynT7fP1bQIDf5nZivXNFJvMkDVgA4=,tag:NoNGvWVyQOPLEELes6KIbg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
