apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:svCoSd3WqxZlObaqlda3fh8qdbFsbXlx/WNWxYw+Aks=,iv:GZYRum/U4zji0c68lH2GiXyfOkD+MjlRqvDSbnJo7C8=,tag:+wwkh2LHRM0Dbd1ujvlzWA==,type:str]
sops:
  age:
    - recipient: age16j9w80ug9xx2cuq5qav6n69c3uuvmt4dlqys2y3l24lmqh72a4csuevy68
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDeW91NzdGTSs2N2JTN2xE
        K2plWlluRUF2OFlhZGo4SHEzM2p6aGxWaFNrCi85N29CM04rZzJtcnM1VnUvVXJZ
        c3dIcGlGRUFVbC9EWU90QzV1aXVDSUEKLS0tIHBBb1RGTGJyd0VUZXViV1lWRDRD
        OVgvSUtxZGF4dERGTVR4MjU1MnNTc1kKMFPkGpTaFjUBqIFqRgXbAm+aefxLaUAR
        371ZW+iP5wJJYl3RMZ3mltAGThrszppxVFLKaxiQAr7nKGZZo4NANQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-24T19:30:01Z"
  mac: ENC[AES256_GCM,data:dV3Br6rXKFTf22OolyeY/qPJ/VeDMmcvIQL2YnjcUdRIwZP+Yn0t2Au9znQEL70GLdc/Lq/K0aC0lnIhhHyhZDLTrs/BsdzheFPRDMlZig5DiaKRxI/DWT5bi9FEdOfxmMAubXDKOgsDEKFDQE1Zh/ytJ4GOXkEjD8/AlAdDiuo=,iv:ziS46jcT1txmeV8yNzT8NXNhfPHaDh/cgIbvPswpNyg=,tag:Ma0SpZa9iI9/XT3hV4eRRA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
