# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:N3CYzs/QQcpGgOpSfFKGPjcIytDrvQw674z3dBz9fjA=,iv:t9kj8n4R7eMwL91CYnoaflTjrp/H7tnS4XmT6KdKT8s=,tag:gJ7um2+D4ab1lRDQYPxDJg==,type:str]
sops:
  age:
    - recipient: age17xhzltzn39ue9gvrv8te7jcf2ns8fz6w07h6djeu20xfucf4vg7sx5ctc6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBibFcwWnFtR0ozbElqTlJP
        R0p5SlFDZzcrUDZ6WUFQdlVYM0FzRFlSTUJFCjk2eUdJanVPajVxZjJOdDhyVE1r
        SzVsQU50QUlncWw5c3RrN3ZhM2lsYzgKLS0tIDRYTG13dlFjeFRjMEEycDMyYkFR
        SFZMeXZzbGxSb2hPdkIrbERSbzBneE0K7evLf85qiUNgz4d8wWK3kUDGMtlyL/Vi
        9kMU7Frl1q7xdi3qRyBfRAhhwivYyAbUBAsk09B7LnzxK0ulGoBscw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-20T16:11:57Z"
  mac: ENC[AES256_GCM,data:SDs1oWG/yseQK1wDFCccPPKZBSx3/64P60Zz7BpFnQP+SDvcGeGdQ+zqkYjkJUO9DlJfl+MVnQqLtVW3jxD6FKiXEuK7NI/V0MdmTWjf4qa0Vhfl52FHnZMxmVmHyua4aSSL2aEnALU7iM9FrEN1XbR8fq11Lu0IwEnjAjo/auY=,iv:Is5d6LVT2Q7euf4OccfpN93Tt7RezJuXAN1dKoyFOgE=,tag:nrHfpZQsRM80aPLu2OFxWg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
