apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:yWcmAI3qLSAtb2RKGLAPu9EYg1bHsAMoh4eRUHdU3s4=,iv:/THY3xe3LfLLS4SEM+WOgRzA7eBI11akW178zCmO2zk=,tag:W2PbzmJGJoOIbglZ26wTfQ==,type:str]
sops:
  age:
    - recipient: age16j9w80ug9xx2cuq5qav6n69c3uuvmt4dlqys2y3l24lmqh72a4csuevy68
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZU0hnRElpenpTY2hqWW01
        RlZzMmVmVVRlOEhHaEdvck8rMXJ1VkloV3drCnlBVGt4cHluM1pSbmF1YlF3Mzh2
        aG43TVZ2K1ZpbEEwTlM5OUdyZnlOVUUKLS0tIGVlMXBtNDBwYVZzT3pQY2l6NFVw
        MlJVc2JYVWZscFNPWm4rWlNzZGdvLzQKea5a8pWsuHqO4+Y2MmPAx5YObMNQi79B
        hTXgQaDUbiNRst2cpRRDK08vArboGgH5GjrWjbfJ5Q0zHUOJs/B5qg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-24T15:23:30Z"
  mac: ENC[AES256_GCM,data:NPTFzNd+GgqZRupZ6p0KnE5BW/79L01KkmT84Zy8puU1c59wqqg2vr3zbEhIAwIbJiuKzBPehl25++q6IaMyoEKSAyhgfT9kcHnVSK3rvtoue9IaGw5H8jbgl2Ne4Bu23qzuWT45IL6dQBJn5W6IchkKY90Fa23updqs5Vrtagg=,iv:ouqQt+66kuJXNlEYakFVssmbdASp7RGNGO+Gu5YpORs=,tag:ee5dWJAezf5+DZt1UHIxxw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
