# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:Zf8k61p140XMOWlBIgzbGxcEeWtP1C6Xg3Icz0AiCWE=,iv:4DNdcnfUGV/l0pzYKh8F6MiPfWkBuhiCrbdA0TounoQ=,tag:x1Y/axlZ3nbub9Y1Nd6OAw==,type:str]
sops:
  age:
    - recipient: age17xhzltzn39ue9gvrv8te7jcf2ns8fz6w07h6djeu20xfucf4vg7sx5ctc6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzN1VXQU55bGJNcHlVT2N1
        Mm9Fb0NGSUxnQkV4ejUzOXZySHhDQ3R4TTNrCmgvVGJ6Wm84MW54WTZBU0tBVFdn
        bllBRWwwSW5yRnhzY281UXMyU2JEWnMKLS0tIFNRaFl6MG9JeElLTzdHUnlqR051
        dGk5VjlDTTdjRkN2VkFVczBHMWZUOHcKjNnRpa4Q39/nYsYqJ5n9eDjBevjMLDXd
        NhyqzE92cITZ70XQM87DqxUS1PtdW7i6d113Z0n8+oTBslHVUeKefg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-20T20:31:37Z"
  mac: ENC[AES256_GCM,data:nMcRGpLCPca/DGueaXTFXps5j4aPpPU5aFNINfxUl2NP5Py8XFbclDAgNF6W/X8d28P6xyPO+LZMkEJmG1FSQOsYqKfYq6EGN7tvd36dMzQ85i5HyVSljenOK4lciW+Hn99e7mC/5yDSwFSF0ufpllP62igsD0l6sEI5PrDZjN8=,iv:A1pg5gfm7e1dWODLuAg5I8pbRRlr5wOEONFYpgorMfo=,tag:Kpg4nEapT5eq8gbE1k4Lbg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
