apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:df2P22rIMfMMrDgUlxT28naDyAqhXWR02O+6iqdVzKcrARVs5xeKVDIxzNPdEiMgHav7igHXtLRxBdM7pQJ7ZqCWB7eBqIuYMRZFZoRIG5771mHA28qAaQwvL9sBC/GDSNsRfRo2HU7rpS7YnLLgiGM873ko6x2jICAV7GcpTtGPMgIio6kz2/aVDN/MdM0SqKoF9Fr21ybc7iVSjPzTAUX5PDj4qIGmK/aa+Igu/JHmHU8/,iv:D30K9YcU+zDlp5InBpCHNpzhMgVksjS8+rsZuhfIOmg=,tag:I3LVCcNBhTL6cWqMnBdaDA==,type:str]
sops:
  age:
    - recipient: age16j9w80ug9xx2cuq5qav6n69c3uuvmt4dlqys2y3l24lmqh72a4csuevy68
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEWnA4MWVNU1Zod01MUkFn
        VllTeHpuV1A4YmxFSGx1L0xKcUx5dE9uNUJnCjdFY1EreXRYclJnTjhmNEQwcFl5
        V08xVTNQekZranF6eHdpN0JhOUg4WDQKLS0tIDdCeS9JU0JidEJaaWErTVR2Mnhm
        MWFLOGNWd013OHREL25QNWZPRG1rbmcKGmsvQYKuaIaDhsUdiwJxrDA1VsYsGxJL
        bCa3iKIpGRu6zIx34z49p6NxE0aK9pZioKwCboq+gXggqEts+pV4Pw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-24T15:23:30Z"
  mac: ENC[AES256_GCM,data:Fsvq/wGWSNVXCA2FspAkRSlJX5JK6vhBbfm7ppZ7iEx/gRL/iHK1MJu8C70nA8AlkUEpItJVggJq9UO3i2S4UYGcJxd+9U6ftIsHDF+WVOrXtBQefANE8eNOiimURPqoagAEcVB4liotl6z8q6xcXa3kCVldsskM9X5vDAGH8sk=,iv:wQWoIz1gbierSdvIGE5dIl5R42KeojaYam78dK9/1wo=,tag:KIZYLnhqaAqzCl8W0Ev6Fg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
