apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:Pm/AqJC37Nzf2Asonz1kvohU/XNN6W8LKUdmhGSI+FWSzXKwlEL8cGoWhGpsuuGvp+Kmu7t3p5xIYki7OZ1gSstplZmzJxYQ4zEknRjlJkpEDyucFkqgkpsDNLCuBw2bE0PrTIWM0anOyMS32ppJW05eaOrwsdvG85F427Ft8ciZepuxrx8juaNZ28xA6vbGI4uVFP0XMkngufEAJMUZdkVjVHsktAN2wvfYi2v3mr8jK425,iv:Wtqry5pzIhpQfA0RaDT7OK3TxoUWj6pGJchAMKc4pgc=,tag:FyM0S1c7sXEZdA10hctW6w==,type:str]
sops:
  age:
    - recipient: age16j9w80ug9xx2cuq5qav6n69c3uuvmt4dlqys2y3l24lmqh72a4csuevy68
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvR1BqOFJuZmw2cUVOajQ0
        SlJrd1JRTXBrYU1LOERtaUFVNVdlcWVoVXdBCitsM24xMFZDTGdiZE91dGo1ckJK
        TXlWNWlsOEQ1TkNXMmgyS1g3YW4yeFEKLS0tIG1lbkVndnk3S0Z3V2lJK20wa3cz
        VzFZYmgrZ09XSE9ob1pMVzhncEc5M3cKmVQBEYOx9iD5VD0ly/xCbUwSB2Dp8yyP
        EvVhGp4PJ538oQiUpo2r1h60TV2J2Rxy9mXmq0qMwPW89OoePZoFCQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-24T19:30:01Z"
  mac: ENC[AES256_GCM,data:PXTO42/E6rpxvwmtUfBAdMmUUD16DgpM7LiYDtCZAV64mQVu4cQrD73bh0TKGf2FrAlDlFzUT0PXVK6OrAPIgnT1Gkw/XYJcoE81QU5Owa2oPjXhLd9wKxdQxPXkXuSLPI3o5XdPSc7ZyCygRC/J1+5qeJ6m5nmPzuKEBfziK0k=,iv:OtJPfsonX6Wm1posMaZ9EBX7WexDl8ZAH//kiaya9hI=,tag:ZRFmQZfxQBlAUEDnfjQ/Sw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
