apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:nRdXJdW3u5bzMw5HQB2MVmJOCOdAYY1xJpvfPCBcdU4c/7AXEW8CQw==,iv:gu7GCkPAyAwTSJU+uFNPuUSesVfues/0tGW1ewofFA0=,tag:oo6GQg/aLXclRVOabQMl9w==,type:str]
sops:
  age:
    - recipient: age16j9w80ug9xx2cuq5qav6n69c3uuvmt4dlqys2y3l24lmqh72a4csuevy68
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVTlpJZ29OZmc4REo0MGVq
        d2VudGhSMmdmbjV0YTJRWWE3K0FCUEczbEdRCmZBNUlTallIdmlRdGpKNFM4VjhE
        aXR0dXpRTjVhckxLUGZsWHN6MWhJY1EKLS0tIFFBRklxVWxweWxrbGFxb3NGZ3ls
        Qi85NE81NTMzSC8wU2dVMmxqUmxtQncK+gxggzoaQ2mkJrPVa+3ZdZK301NMBWIC
        mNqZuVLFc4IErAw6QsT+BVVsqCKRnm14rNR/6wOFrcSnz+FgDNwmqQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-24T19:30:01Z"
  mac: ENC[AES256_GCM,data:UbHmXskvWOs4bGOVkeUj6TNsWcsOsteRSVB27orUE8fvGQMheCTUW45xFlCDL3xuiWcr+0i5q9KUfALFJtRT8/ycwdvs4euYkLJL5fSoqHgH3ZbPN7fUNvy/cXEFmguuQOQgdAp7MG0ark0AVOOLbp5M8+mbq8xXipZLPA90YqI=,iv:ZJQtxj6VPpz1QGrQhLob0oJaV+vbiLnjmJOj7zvTwGA=,tag:7PdgpH/FarsXoW9vYXoc0Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
