# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ""
sops:
  age:
    - recipient: age17xhzltzn39ue9gvrv8te7jcf2ns8fz6w07h6djeu20xfucf4vg7sx5ctc6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlQm1BWkRwZi9lMjAzVmFM
        cHQyMEdKNytwUnZ0dWxtemphVXM2ZlhyL1ZVCkI1WmJ2RC9JRVpiNjZKZmliU2R0
        OFNLaWRhMEJGcWdkRXBNWlF0QzMza1EKLS0tIENweEV6N0d0RU0yVUFoOGhBbGFE
        SHRzeXBIdk9LYnI4SGl5OG1uYnV5bTQKS14CF5i1LWG5N4hdaIzcvOFRK/JcO+3S
        2O5BZuJwSCCLFlo64zf6+QC4J1qWJeNqC+6rH6aklqmku3ID0aSuPw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-20T21:31:31Z"
  mac: ENC[AES256_GCM,data:jgncy6ksCJAqWq0WJz+f9sqU/hwUeA8AelkgzaA9cAeSRxse0T1r3UNqgROiRWXiZ1SI+7D9P27HPH0TsKaV4iB2Nn1i3ACZNoHtRuXF235zhKjxsieOhGsnVMI49OL61Col2sGavjQ4zyF0F9TG0ZVwSnf4ZJB21DviCMKqpG0=,iv:B+YjWVh19gWAs8QTR2SlWQGuiYKxaMaoQ/8yJlGsyXo=,tag:rwQVui3V+vo6IGIQAbFutg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
