# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ""
sops:
  age:
    - recipient: age17xhzltzn39ue9gvrv8te7jcf2ns8fz6w07h6djeu20xfucf4vg7sx5ctc6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5QTBSVzZCVUhDU0thOGdi
        RUtvb0FtaXJBWmdaUHg4UGtmaGxScVFhcnhJCmU3TCtuTmRncFJmc09TL1hscDI1
        NkxuVE5KWmc2WlZQNFhCN3JnTG9KZmcKLS0tIHJkellYZ2h2K1I4Z2pheisyamlK
        V3lVaEF2eFVXZUgweXZKUmZkTytRRm8KU1Fpn9TGM2skA6tw6yQ4D3+CacKPo09g
        cVW9BZ9m90hGG83FmN8gMxLkIbU1NbAlABx+qeCcoTea/pnYBJgMfA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-20T12:57:48Z"
  mac: ENC[AES256_GCM,data:CTBqORnTfKMb4/QYObR6o+QdoGR4/0bCuS667gc9Frbh4RQIpC2EdgxBoq1Xtw1rfzJE4p/DgEyfK67iZDcjm6psQImwqxc4TWrKzS7u5NgU4TfdILS7FZjgwmgrIK6+V4XhCjonKf0xErn4ro7oOfSVpOIGAPiqnYT+qkQSKH8=,iv:fUD/UGDwh2+lyqvSFiJsFy3F2HRjviNlG1kjcrLU0Eg=,tag:iWLrwGnfhPfew3I1CuZfKg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
