apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:PLawCxu7fJaWFB4uM8X8yGG/0Aygk8zQYG04UvTfDj3KkhdgwzgD4Q==,iv:S6KXGif9e0eOUrO5kr6Ed7DcwdPNED7eUhR7CFTs7d8=,tag:aidhmWzG/ccPodSuk3DG0g==,type:str]
sops:
  age:
    - recipient: age16j9w80ug9xx2cuq5qav6n69c3uuvmt4dlqys2y3l24lmqh72a4csuevy68
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZeW9WUlBMbWRwdjlxbHZx
        L1NhSjdYNmFFM2wzMjYzUEszaHFZVWtRTm1NCkJsdlU4ejJtZkhZOWJlSlJ2VEky
        UDB4VTZsTnJUWDdOZXlhUDRXaDNCbGsKLS0tIGM3eUU0ZExiZGE0UHpCVm9BU0tK
        VytoVmZNUHo5cnl6Y0xMYkk3TldRQWcKt4yeGn2EFGtpYD4ei8Zccvmlla7AGqDy
        v41DAoaJBlkalsdLHeG0TWy2BaQCJhkNwlf3IRhf6c1IJj0YC5gpnw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-24T15:23:30Z"
  mac: ENC[AES256_GCM,data:TruZc4sZxdBf2nLYQq+4T4qg14MsHodJL7M9edpwspd6AqEiFfAEBPCO+5bb1AlfMgB6YqeKwuqlajlbxF4tHEFN0QXsqoN+WUau+58Mfgo9hyLWSw1HNauNj2JBmSRs2zslZKTsjBbM+wPuncvj4oeEvrTRYzjtRZH+ECTIY1Y=,iv:IUavqzoTFO0xOQl7ipL/kGUqXyh7i3sZ1WfhgSakgKw=,tag:GMWTlt9ht/Z6DWoGhzVhvw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
