# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ""
sops:
  age:
    - recipient: age17xhzltzn39ue9gvrv8te7jcf2ns8fz6w07h6djeu20xfucf4vg7sx5ctc6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKZlNUd0FYbVZVUU13Ri8x
        SnRtUDhVRkVJbUE2QXRqeGpFVTNsZUUzeURnCm1KRHpwRU5jZ3lhNjZBSHVueEJB
        anBEZDFrT0pQNytpTWNXZzc5YVdGZTAKLS0tIEdLVjhiSzFOMUUwL3U0LzZwT0ts
        bmRwV0xvRUYxQ0pQaHd5WU9tZ1hJYzQKzfzLDzPBf6YacAJW+uK2Ajl5DjohTgwc
        SJkJ29F8VsjiUvoUrHjZEwLWdH6SWkuRTl1ZyA2p5XFUhzUR/W1zbA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-20T16:11:57Z"
  mac: ENC[AES256_GCM,data:wPAN6cxQOKYC1UezGMpffEZKe/AQeOFOIJmfjMirCgdfbzWZ+Jj+xeeZRWuy/Grj9LPAMc4l0ff9uoeBbHHxLvXkHpJ7mmR/JXzRqArNrivphx/fScpq3GhV2Zm3r99WA1oHXDjxhuYsamU3K3mUzyUh4yzdl5wwTZ2vOR3a1ic=,iv:WABsN/9OZF2zJLx5MbugWf/Huou5JRLoyvi6eu8qsRo=,tag:n3VwrsBLQi0VlFj3NZ7cNw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
