# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ""
sops:
  age:
    - recipient: age17xhzltzn39ue9gvrv8te7jcf2ns8fz6w07h6djeu20xfucf4vg7sx5ctc6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqa2hmbTVQQXhlQUJmdFN5
        UGdqRHQ5M3NjbjZVdTZ5WllsdTIxTUNCS0RRCkdpekU0OEp1d0w1K2M0OTBISGRw
        SG5wR3pVWlBZZWQxUFRZY2RMSzRnM1UKLS0tIGpSYUwvNTRjVDNQeHVON1hmR1Jh
        cFFSSmlHNENlU01JazF5a2ZxeCt3a2MKJQJsgFlls222OVg6zXC/Tpv+q+lkXR7L
        +9UQKJ0OYiLTySizaCfTtllmNhVaD5HRB9Xl+Sta6rnV/Vbw45LRkw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-20T20:31:37Z"
  mac: ENC[AES256_GCM,data:tL0FH2BZ7+qLMtul1HBbcNLQEyXejWAEAwEN9OnP6BA/bnOZJuyOy49E0q7DozH12z1w1bgfPz68ezzXOTHxCQy8pYYavhCU00S6GFK335oksgR6ecp35u9Vba9v+ptqM0Aa1/TQFwJhwW8ZL61qa5cVGvbI1kC8HEgoSuI0uHY=,iv:preJCtyHyXXTZtcGJyrRtBbq5ZVdX2bVp/acN0E5JuA=,tag:hvIjfriYzML8KBCkd7XeJg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
