apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:4XoHEijjuuokoX8m/w==,iv:12V+df8z+o1TpbyambcECldbIX4X5JR9jjl1haWnwUw=,tag:5FPrL2THyI08oKp9e1GqVA==,type:str]
sops:
  age:
    - recipient: age17xhzltzn39ue9gvrv8te7jcf2ns8fz6w07h6djeu20xfucf4vg7sx5ctc6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJRE14aVlkZDJqTDRFNFcv
        ME9BVXFyVnhTaDlSWG03eklVRWFVZEgwNFZnCkxQZU4vYWJCSnJDMEFuazFlOVc0
        UjlhL1IrZUp4VldsSXhCZWJMaUpBdkEKLS0tIFI2SGZCT015Qll2YnVRdFh6ZVJI
        blpXNU1TWFQyMHRFYnk0clpTdDlQV2sK0u7phqDGYs/qBzGVU4UpZzfg1PUYm3fD
        ePt9CNxuUlIvYjo+xUVQtgWtxHSimwVaP8sVj2T7zgcJ7WuWIhMJpw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-20T12:57:48Z"
  mac: ENC[AES256_GCM,data:JzegzNQ5JX1LjsUNqk3FfSY0OjsiIRTRp4S6eg/KlCh/ZaLT21WMGH594qDuTJp8JTnqr0sXhN28vDuq+HAPQL2SjKOW7KoRINXRyQ6Z8ecFZvvRCmde1sw+kWRFgw1aADVHlIvsVV9n0KHKrpHmigfK7YjU7tUvYdJnLuVXktU=,iv:fDAJya50leq7GtaZnC7ChTCZc56CYiU5CHVT2MsLoq4=,tag:z1Lj15tzUjcW/8KDnrPSUw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
