apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:S4oASY7xGsC31AOwgg==,iv:auGfKVFcwKu6l/nUZ0GAGXLT/1Ybtg+li44W6mkvea4=,tag:BuDbTaSKqIpYwCTGxTrW+Q==,type:str]
sops:
  age:
    - recipient: age17xhzltzn39ue9gvrv8te7jcf2ns8fz6w07h6djeu20xfucf4vg7sx5ctc6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByYVJ5VFc0NXNIYVZKNi8v
        WVAwbjQzd1VDZzh5Si9SUUZiZDd0Zzk0NlVVCkl3dE1SdDFDRjI0N2dydHRGQ0Vx
        Q2tLbllwQXM1N2paSXY5M3Q5dUZvWncKLS0tIDJ0MmhWU1pEK2tpWndWakFhSTVo
        Rm8zWFVaRHN4eEJLLyswQ09NSzVaWDgKJciHITgbpnUmZaXk21oSQkg16D+Qc0/1
        9HwnLskAunfokj5tu1Ps5Eti8xXBcDKw3EHisshxaU09K6i5NFnNVA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-20T20:31:37Z"
  mac: ENC[AES256_GCM,data:u9lC3myoGWaozlpV9gRFah1z4i0drCmED8shNwGIv3yQfHj6hvh19kcF6Yx0eOxBHoeurTI9VGqI/PKpGkBlT5h7yFGxOjalBN7Tf6KH96Mi3jsxkfQZ0ojSqAHYL5K86IB6aTModNE9eN7Jc6NmURzZAyrSqrphXfytugS4i20=,iv:bcOaai7i9lDhw/6o7irgWD0c08wz/t8fV+ugBKudCrA=,tag:XjWl5y2wVTfaCj9oRzEwQg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
