apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:ViwtPeQ96ec4n0O1Jw==,iv:0Uy3eZ8PjhsqcSuQBBxU5Ux2PUbXodELaM8Qy0RbGLk=,tag:dC9ITLDfohbCP/U0DUdigA==,type:str]
sops:
  age:
    - recipient: age17xhzltzn39ue9gvrv8te7jcf2ns8fz6w07h6djeu20xfucf4vg7sx5ctc6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDRlNlL2xuTHFVaGhlSWdk
        MTRyeGJ0WTg5Ry9KZ0VSTllVZkc5TW1BL0dRCjRXenRJcTJtNEJJUFNzMERGZmZu
        VGlwcHNSZVdJRWxTNlJkQUh2OHAxWHMKLS0tIHdTS09hL2pyLzNRK2FzS2FUb1Zs
        V1NHajFGOUFPUExFVTZpREJPOS9mK00KqQhgFk3qbMRKS/gRYrR7tm1MGL40o90R
        E4R6KU+nxyPwdwlAqYNuFKkdnQlm3R6SrGr8YGMpBPFL6k0cJ6Orzw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-20T21:31:31Z"
  mac: ENC[AES256_GCM,data:0L9UNRKINLTaTvLY0/8HrcwHm99Me25+B/cefWmeW6zzzL+QEdpBtAkSkGW/P72uGh6HMQqA0R+OlT4JS4LU/p07q6ula4I26S4Y2UzKY5fWcBgpDH6rnI9LKkRSExE/E8LrgJuwKlbQLm7Bp3K1I5cDBbbPN8CUDCeQzq8TO0U=,iv:wZCo72EDkdVPOCTZ5S/uV2tfpAeFlKw0/XF+p/kIu90=,tag:sWktKVKENBW+P2uL8Yz8tQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
