apiVersion: v1
kind: Secret
metadata:
  name: sops-age
stringData:
  age.agekey: ENC[AES256_GCM,data:XvJG8xwK3zUPSrPGetwx+XqLH8+RROib2paP5xpPxNuelT7y5jmeGDpfVWRKSBb711eiPzofhEBxxTWqd4pFEC0wQn1tlpZzQZQ=,iv:NVm0OUPV8MOQEtDWXcNJJEZHDzlB29vQVuXrcI8GQ8A=,tag:L7Z4QbYlORQq3aae5WnR6w==,type:str]
sops:
  age:
    - recipient: age17xhzltzn39ue9gvrv8te7jcf2ns8fz6w07h6djeu20xfucf4vg7sx5ctc6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCc3dzM011cEhBUDNSa2po
        WE5wdERaWFZzcVU4VzhkMW9FaWxHZFJieTJZCmZwV2owOXhUU2UwaS9PbWthd3Rw
        MDRud0lhQUUvajQzbTR2YTBKQkt2YUUKLS0tIDdta3Zvc1JaNGlFaUZ5anpzMW10
        UjlBWjBZUDFHcE01bW1jRU1ybE54YUEKdtqsTDg4EOzu1uAeIhvYk9ob/tiv0R0P
        Ogo4NSYsHoweRVF4gBw07dGV9Ey+vh3JqgqNohKsY+E6aSbJdXh6QA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-20T12:57:48Z"
  mac: ENC[AES256_GCM,data:E2SednyM8EFiLwEMsXjGBbgJ4IDE94OMBX1Z1m6m6aun3N+Kk5c/csa26cXVL7aWPbqXkuC46FlF35iU2lDPChqTWl+83SVSSvd17+qTSJiH6sKuUlZ3mhjADQ/zm3YFUQ5TJw099RBDizNseOI230LHeYpQee4yYyJHW3KpaAQ=,iv:ahITNHv65bet74wDaasATYPf4Ru+ZVcPbSSzVhvE5ok=,tag:ycGQhQVFBLTqBPFMld+hjw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
